### PR TITLE
ENH: Support importing pre-existing cameras in automatic VRG generation

### PR DESCRIPTION
**Pull request by jcfr**
| Before | After (Automatic) | After (Load from directory) |
|--|--|--|
| image | image | image |

### CODE REVIEW

**Comment by jcfr** [comment]
| Before | After (Automatic) | After (Load from directory) |
|--|--|--|
| image | image | image |

**Comment by jcfr** [comment]
@amymmorton Could you confirm that the proposed design would address your use case ?

**Comment by amymmorton** [comment]
Yes, this looks like a great enhancment to meet the request - thanls @jcfr

**Comment by jcfr** [comment]
Thanks for the feedback, I will move forward with the proposed approach :rocket:

**Comment by amymmorton** [comment]
Also suggest closing this as a development path no longer being pursued in favor of 3d-3d

**Comment by jcfr** [comment]
Closing. This become obsolete following the integration of commit 7d1de4d (ENH: Hierarchical approach to 3d registration) through pull request #99.

**Pull request closed without merging**
