### PR TITLE
Tracking evaluation module

### LINKED ISSUE #30: Ankle Sample Data Filter
Based on the ankle sample data @amymmorton showed me, the images may be over-filtered. I've attached the text for the .vie file our lab uses for ankle data. 

RadFilters_begin
SobelFilter_begin
Scale 0.5
Blend 2.1
SobelFilter_end
ContrastFilter_begin
Alpha 3.9
Beta 2.7
ContrastFilter_end
RadFilters_end
DrrRenderer_begin
SampleDistance 0.62
RayIntensity 0.49
Cutoff 0
DrrRenderer_end
DrrFilters_begin
SobelFilter_begin
Scale 0.53
Blend 2
SobelFilter_end
ContrastFilter_begin
Alpha 0.5
Beta 1
ContrastFilter_end
DrrFilters_end

d

### LINKED ISSUE #32: Support for evaluating the accuracy of the tracking
image

References:
* https://github.com/skelobslab/JOVE_BVR_FootModelAndMarkerBased
* https://www.jove.com/t/63535/biplanar-videoradiography-dataset-for-model-based-pose-estimation

### PR DESCRIPTION
**Pull request by NicerNewerCar**
* Adds new `Tracking Evaluation` Module
* Closes #32 and Closes #30

TODO:

- [x] Support loading partial volumes, tracking data, and GT tracking data into Slicer.
- [x] Visualize the movement of the partial volumes.
- [x] Fix issue with transforms
- [x] Visualize the difference between the tracking data and GT data (see diagram above).
    - [x] Models should be green iff the difference is within some tolerance (ie. 1mm or 2 deg).
    - [x] Models should be red otherwise
- [x] Update the current frame to be a spin box
- [x] ~~Add reverse option for playing sequence~~
- [x] ~~Add pause button~~
- [x] Update the [tutorial](https://autoscoper--117.org.readthedocs.build/en/117/tutorials/sample-data.html) or create a new one to cover the usage of this module.
- [x] Update the Sample data to include GT tracking data (Update the Ankle filter for #30 too).
    - [x] Need to update the [release](https://github.com/BrownBiomechanics/Autoscoper/releases/tag/sample-data) in autoscoper main.
    - [x] Need to update checksum verification in SA^M:
https://github.com/BrownBiomechanics/SlicerAutoscoperM/blob/13ae181309b949420dc06c1bac2f894d63f3a3f9/AutoscoperM/AutoscoperM.py#L104-L116

### CODE REVIEW

**Comment by NicerNewerCar** [comment]
@amymmorton You are good to start testing this branch.

An updated tutorial on how to use the module can be found [here](https://autoscoper--151.org.readthedocs.build/en/151/tutorials/loading-and-tracking.html#evaluating-the-sample-data-tracking-results).

Note: Only the Wrist and Ankle datasets have been updated. Still waiting on the knee.

**Comment by amymmorton** [comment]
inner failed to compile 2x..
trying from fresh clone .. will update

**Comment by NicerNewerCar** [comment]
@amymmorton If you could upload the build log (from the output tab of visual studio) that would be much appreciated.

**Comment by amymmorton** [comment]
got it..
trackEvalSucess

**Comment by jcfr** [comment]
Topic has been re-based along with integrating the following changes:

* renamed variable
  * like `gtVarName` to `grountTruthVarName`
  * like `seqSomething` to `sequenceSometing`
  * `colNames` -> `columnNames`
  * `fName` -> `fileName`
* renamed method
  * `updateColor` -> `setColor`
  * `updateGtVisibility` -> `setGroundTruthVisible`
* fixed typos reported by the newly integrated codespell pre-commit check
* re-ordered imports
* removed unused parameter node member like inputVolume, imageThreshold, ...
* removed obsolete setting of `inputVolume` in `initializeParameterNode()`
* removed `-> None` (having them included them in the Slicer module template is an oversight)
* fixed `sampleDataType` to use the updated folder names prefixed with `2023-08-01`
* removed unneeded update of `sys.path` in `data/__init__.py` 
* update annotation to use `list` instead of  `List`
* prefer f-string formatting

**Comment by jcfr** [comment]
Considering that I am able to load the `.tra` file exported selecting `All` and compare it against the relevant "ground truth" data set, I am moving forward with the integration.

Additional improvements will be integrated in follow-up pull request.

**Pull request merged**
